spring.datasource.url=jdbc:postgresql://localhost:5432/vendor_db
spring.datasource.username=postgres
spring.datasource.password=rama

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.file.name=spring-error.log
logging.level.org.springframework=ERROR
logging.level.org.hibernate=ERROR